In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable


Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd

In [3]:
#creating arrays
import numpy as np
arr=np.array([1,2,3,4,5])
#for 1d array
arr2=np.array([[1,2,3,4],[6,7,8,9]])
#for 2d array
arr3=np.array([[1,3,4,5],[6,7,8,9],[8,4,5,7]])
#for 3d array
print(arr)
print(arr2)
print(arr3)

[1 2 3 4 5]
[[1 2 3 4]
 [6 7 8 9]]
[[1 3 4 5]
 [6 7 8 9]
 [8 4 5 7]]


In [8]:
df= pd.read_csv('DigiDB_digimonlist.csv')
df

Number            Digimon Stage     Type Attribute  Memory  Equip Slots  \
0         1            Kuramon  Baby     Free   Neutral       2            0   
1         2            Pabumon  Baby     Free   Neutral       2            0   
2         3            Punimon  Baby     Free   Neutral       2            0   
3         4            Botamon  Baby     Free   Neutral       2            0   
4         5            Poyomon  Baby     Free   Neutral       2            0   
..      ...                ...   ...      ...       ...     ...          ...   
244     245         Valkyrimon  Mega     Free      Wind      18            3   
245     246    ShineGreymon BM  Mega  Vaccine      Fire      22            2   
246     247  MirageGaogamon BM  Mega     Data     Light      20            2   
247     248         Ravemon BM  Mega  Vaccine      Wind      20            2   
248     249         Rosemon BM  Mega     Data     Plant      20            2   

     Lv 50 HP  Lv50 SP  Lv50 Atk  Lv50 Def  Lv50 Int  Lv50 Spd  
0         590       77        79        69        68        95  
1         950       62        76        76        69        68  
2         870       50        97        87        50        75  
3         690       68        77        95        76        61  
4         540       98        54        59        95        86  
..        ...      ...       ...       ...       ...       ...  
244      1330      139       148       129       129       168  
245      1980      114       228       104        84       168  
246      1440      124       178       104       158       174  
247      1040      133       149       139       144       213  
248      1480      143       149       139       159       143  

[249 rows x 13 columns]

In [9]:
#Select row based on conditions
#oprion 1
df[df['Digimon']=='Botamon']

Number  Digimon Stage  Type Attribute  Memory  Equip Slots  Lv 50 HP  \
3       4  Botamon  Baby  Free   Neutral       2            0       690   

   Lv50 SP  Lv50 Atk  Lv50 Def  Lv50 Int  Lv50 Spd  
3       68        77        95        76        61

In [10]:
#option 2
df.query("Digimon=='Botamon'").head(2)

Number  Digimon Stage  Type Attribute  Memory  Equip Slots  Lv 50 HP  \
3       4  Botamon  Baby  Free   Neutral       2            0       690   

   Lv50 SP  Lv50 Atk  Lv50 Def  Lv50 Int  Lv50 Spd  
3       68        77        95        76        61

In [12]:
#combining conditions
#option 1
df[(df['Type']=='Free')&(df['Memory']>2)].head(5)

Number   Digimon        Stage  Type Attribute  Memory  Equip Slots  \
5       6   Koromon  In-Training  Free      Fire       3            0   
6       7   Tanemon  In-Training  Free     Plant       3            0   
7       8  Tsunomon  In-Training  Free     Earth       3            0   
8       9  Tsumemon  In-Training  Free      Dark       3            0   
9      10   Tokomon  In-Training  Free   Neutral       3            0   

   Lv 50 HP  Lv50 SP  Lv50 Atk  Lv50 Def  Lv50 Int  Lv50 Spd  
5       940       52       109        93        52        76  
6      1030       64        85        82        73        69  
7       930       54       107        92        54        76  
8       930       64       108        64        54        93  
9       640       86        76        74        74       103

In [17]:
#option 2
df.query("Memory>2 & Type=='Free'").head(10)

Number   Digimon        Stage  Type Attribute  Memory  Equip Slots  \
5        6   Koromon  In-Training  Free      Fire       3            0   
6        7   Tanemon  In-Training  Free     Plant       3            0   
7        8  Tsunomon  In-Training  Free     Earth       3            0   
8        9  Tsumemon  In-Training  Free      Dark       3            0   
9       10   Tokomon  In-Training  Free   Neutral       3            0   
10      11  Nyaromon  In-Training  Free     Light       3            0   
11      12   Pagumon  In-Training  Free      Dark       3            0   
12      13   Yokomon  In-Training  Free     Plant       3            0   
13      14   Bukamon  In-Training  Free     Water       3            0   
14      15   Motimon  In-Training  Free   Neutral       3            0   

    Lv 50 HP  Lv50 SP  Lv50 Atk  Lv50 Def  Lv50 Int  Lv50 Spd  
5        940       52       109        93        52        76  
6       1030       64        85        82        73        69  
7        930       54       107        92        54        76  
8        930       64       108        64        54        93  
9        640       86        76        74        74       103  
10       540      107        54        64       103        94  
11       550      103        60        63       102        93  
12      1040       64        82        82        75        69  
13       830       93        54        74       103        69  
14      1030       63        82        81        78        69

In [18]:
df['Lv50 Spd'].mean()

120.40160642570281

In [19]:
df.rename(columns={'Type':'Types'})

Number            Digimon Stage    Types Attribute  Memory  Equip Slots  \
0         1            Kuramon  Baby     Free   Neutral       2            0   
1         2            Pabumon  Baby     Free   Neutral       2            0   
2         3            Punimon  Baby     Free   Neutral       2            0   
3         4            Botamon  Baby     Free   Neutral       2            0   
4         5            Poyomon  Baby     Free   Neutral       2            0   
..      ...                ...   ...      ...       ...     ...          ...   
244     245         Valkyrimon  Mega     Free      Wind      18            3   
245     246    ShineGreymon BM  Mega  Vaccine      Fire      22            2   
246     247  MirageGaogamon BM  Mega     Data     Light      20            2   
247     248         Ravemon BM  Mega  Vaccine      Wind      20            2   
248     249         Rosemon BM  Mega     Data     Plant      20            2   

     Lv 50 HP  Lv50 SP  Lv50 Atk  Lv50 Def  Lv50 Int  Lv50 Spd  
0         590       77        79        69        68        95  
1         950       62        76        76        69        68  
2         870       50        97        87        50        75  
3         690       68        77        95        76        61  
4         540       98        54        59        95        86  
..        ...      ...       ...       ...       ...       ...  
244      1330      139       148       129       129       168  
245      1980      114       228       104        84       168  
246      1440      124       178       104       158       174  
247      1040      133       149       139       144       213  
248      1480      143       149       139       159       143  

[249 rows x 13 columns]

In [20]:
#Dataframe dimension-total number of row and columns
df.shape

(249, 13)

In [21]:
#Dataframe dimension-total number of row 
len(df)

249

In [22]:
#Navigation dataframe - display rows with all columns from 0th index to 2th index
df.iloc[0:3]

Number  Digimon Stage  Type Attribute  Memory  Equip Slots  Lv 50 HP  \
0       1  Kuramon  Baby  Free   Neutral       2            0       590   
1       2  Pabumon  Baby  Free   Neutral       2            0       950   
2       3  Punimon  Baby  Free   Neutral       2            0       870   

   Lv50 SP  Lv50 Atk  Lv50 Def  Lv50 Int  Lv50 Spd  
0       77        79        69        68        95  
1       62        76        76        69        68  
2       50        97        87        50        75

In [23]:
df.loc[:3]

Number  Digimon Stage  Type Attribute  Memory  Equip Slots  Lv 50 HP  \
0       1  Kuramon  Baby  Free   Neutral       2            0       590   
1       2  Pabumon  Baby  Free   Neutral       2            0       950   
2       3  Punimon  Baby  Free   Neutral       2            0       870   
3       4  Botamon  Baby  Free   Neutral       2            0       690   

   Lv50 SP  Lv50 Atk  Lv50 Def  Lv50 Int  Lv50 Spd  
0       77        79        69        68        95  
1       62        76        76        69        68  
2       50        97        87        50        75  
3       68        77        95        76        61